### ISSUE TITLE
New page rendering 

### ISSUE THREAD

**Issue by anuragkmr45** [shaansuraj/portfolio#1]
as the react .js is a single-page application, while clicking on the link of a new page, it starts from the same window position as the previous one.

**Comment by anuragkmr45** [comment]
this issue can be resolved by 

    const smoothDirect = () => {
        window.scroll({
            top: 0,
            left: 0,
            behavior: "smooth",
        });
    }

**Comment by shaansuraj** [comment]
@anuragkmr45 Gotcha, buddy. I will correct it right away. I forgot to add this. ☄
